title: Image

accept:
  extension: jpg, png, jpeg, webp
  
fields:
  show_on_landing:
    label: Show on landing page?
    type: toggle
    text:
      - "yes"
      - "no"
    default: true
    width: 1/4
  alt:
    label: Alt Text
    type: text
    width: 1/1
    required: true
    translate: true