title: Default Page

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          text:
            type: textarea
            size: huge
  sidebar:
    width: 1/3
    sections:
      pages:
        type: pages
        template: default
      files:
        type: files

options:
  changeSlug:
    admin: true
    editor: false
  changeStatus:
    admin: true
    editor: true
  changeTemplate:
    admin: true
    editor: false
  changeTitle:
    admin: true
    editor: true
  create:
    admin: true
    editor: false
  delete:
    admin: true
    editor: false
  duplicate:
    admin: true
    editor: false
  preview:
    admin: true
    editor: true
  read:
    admin: true
    editor: true
  sort:
    admin: true
    editor: false
  update:
    admin: true
    editor: true
