title: Project
preset: page

status:
  draft: Draft
  listed: Published


fields:
  categoryB:
    label: Category
    type: radio
    required: true
    translate: false
    width: 1/2
    options:
      choiceone: Research
      choicetwo: Other
      choicethree: Competition
      choicefour: Competition won
      choicefive: Direct Commission

  tag:
    label: Tag
    type: radio
    required: true
    width: 1/2
    translate: false
    options:
      built: Realized
      building: Building
      notbuild: Not realized

  information:
    lable: Info
    type: structure
    fields:
      projectDetails:
        label: Project details
        type: select
        options:
          client: Client
          architecture: Architecture
          place: Place
          value: Value
          timeframe: Timeframe
      value:
        label: Value
        type: text
  line:
    type: line
  textTitle:
    label: Text title
    type: text
  text:
    type: textarea
    size: large
    buttons: false

sidebar:
  cover:
    type: files
    label: Cover
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    min: 1
    max: 1
    required: true
  gallery:
    type: files
    label: Gallery