title: Project

status:
  draft: Draft
  listed: Published

tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        fields:
          categoryB:
            label: Category
            type: radio
            required: true
            translate: false
            width: 1/2
            options:
              choiceone: Research
              choicetwo: Other
              choicethree: Competition
              choicefour: Competition won
              choicefive: Direct Commission

          tag:
            label: Tag
            type: radio
            required: true
            width: 1/2
            translate: false
            options:
              built: Realized
              building: Building
              notbuilt: Not realized

          information:
            lable: Info
            type: structure
            fields:
              projectDetails:
                label: Project details
                type: select
                options:
                  client: Client
                  architecture: Architecture
                  location: Location
                  construction costs: Construction Costs
                  timeframe: Timeframe
                  planification period: Planification Period
                  construction period: Construction Period
                  SIA volume: SIA Volume
                  span: Span
                  competition result: Competition Result
                  project phase: Project Phase
                  status: Status
                  construction management: Construction Management
                  general planification: General Planification
                  general contractor: General Contractor
                  total contractor: Total Contractor
                  landscape architecture: Landscape Architecture
                  timber engineer: Timber Engineer
                  building services: Building Services
                  electro: Electro
                  building physics: Building Physics
                  collaboration: Collaboration
                  environment: Environment
                  fire protection: Fire Protection
                  facade: Facade
                  light planification: Light Planification
                  mobility: Mobility
                  steel construction: Steel Construction
                  concrete construction: Concrete Construction
                  timber construction: Timber Construction
                  natural stone: Natural Stone
                  excavation: Excavation
                  publication: Publication

              value:
                label: Value
                type: writer
                marks:
                  - link
                  - sub
                  - sup
                nodes: false
          line:
            type: line
          textTitle:
            label: Text title
            type: text
          text:
            type: writer
            size: large
            marks:
              - link
              - sub
              - sup
            nodes: false

      sidebar:
        width: 1/3
        sections:
          images:
            type: fields
            fields:
              gallery:
                min: 1
                required: true
                type: files
                label: Gallery
                query: site.images
                uploads:
                  parent: site
          fields:
            type: fields
            fields:
              credit:
                translate: true
                label: Photocredit
                type: writer
                marks:
                  - link
                  - sub
                  - sup
                nodes: false

  seo: seo/page

options:
  delete:
    editor: true
    admin: true
  changeStatus:
    editor: true
    admin: true
