title: Project

status:
  draft: Draft
  listed: Published

tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        fields:
          listTitle:
            type: writer
            label: Name
            help: Projectname in the index
            placeholder: EFH/Brücke
            maxlength: 60
            translate: true
            marks: false
            nodes: false
            required: true
          project_Status:
            label: Status
            type: toggles
            translate: false
            required: true
            width: 1/2
            options:
              - value: in_planning
                text: In planning
              - value: executed
                text: Executed
              - value: competition
                text: Competition
          competition_Result:
            label: Competition Result
            type: text
            required: true
            width: 1/2
            placeholder: 1st Place
            when: 
              project_Status: competition
          spacer:
            type: gap
          year:
            label: Year
            type: text
            required: true
            width: 1/2
            placeholder: 2026 or 2023–2026
            translate: false
          location:
            label: Location
            type: writer
            marks:
              - link
            nodes: false
            required: true
            width: 1/2
            placeholder: Zurich (ZH)
          competencies:
            label: Competencies
            type: tags
            width: 1/2
            separator: ","
            required: true
            search: true
            translate: false
            accept: options
            options:
              type: query
              query: site.find("language-helper").competencies.toStructure
              text: "{{ item.EN_term }}"
              value: "{{ item.key }}"
          fields:
            label: Fields
            type: tags
            width: 1/2
            separator: ","
            required: true
            search: true
            translate: false
            accept: options
            options:
              type: query
              query: site.find("language-helper").fields.toStructure
              text: "{{ item.EN_term }}"
              value: "{{ item.key }}"
          material:
            label: Material
            type: tags
            width: 1/2
            separator: ","
            required: true
            search: true
            translate: false
            accept: options
            options:
              type: query
              query: site.find("language-helper").material.toStructure
              text: "{{ item.EN_term }}"
              value: "{{ item.key }}"
          collaboration:
            label: Collaboration with
            type: writer
            marks:
              - link
            nodes: false
            required: true
            translate: false
            width: 1/2
            placeholder: Architecture office
          information:
            label: Info
            type: structure
            fields:
              projectDetails:
                label: Project details
                type: select
                options:
                  client: Client
                  architecture: Architecture
                  project phase: Project Phase
                  competition result: Competition Result
                  planification period: Planning Period
                  construction period: Construction Period
                  SIA volume: Volume (SIA)
                  span: Span
                  construction costs: Construction Costs
                  construction management: Construction Management
                  general planification: General Planification
                  general contractor: General Contractor
                  total contractor: Total service contractor
                  landscape architecture: Landscape Architecture
                  timber engineer: Timber engineering
                  building services: Building Services
                  electro: Electro
                  building physics: Building Physics
                  environment: Environment
                  fire protection: Fire life savety
                  facade: Facade
                  light planification: Light Planification
                  mobility: Traffic planning
                  steel construction: Steel Construction
                  concrete construction: Concrete Construction
                  timber construction: Timber Construction
                  natural stone: Natural Stone
                  excavation: Excavation
                  publication: Publication
                  funding: Funding
                  publisher: Publisher
                  institution: Institution
                  credits: Credits

              value:
                label: Value
                type: writer
                marks:
                  - link
                  - sub
                  - sup
                nodes: false

          headline:
            label: Text Detailpage
          textTitle:
            label: Text title
            type: text
          text:
            type: writer
            size: large
            marks:
              - link
              - sub
              - sup
            nodes: false

      sidebar:
        width: 1/3
        sticky: true
        sections:
          fieldsA:
            type: fields
            fields:
              toggle_detailpage:
                type: toggle
                label: Detailpage?
                text: 
                  - "no"
                  - "yes"
                default: true
                help: "No: The project is shown in the index but doesn't have it's own detailed page. No images shown on landing page."
                width: 1/2
                translate: false
              categoryB:
                label: Orange Bar Category
                type: radio
                required: true
                translate: false
                width: 1/2
                options:
                  choiceone: Research
                  choicetwo: Other
                  choicethree: Competition
                  choicefour: Competition won
                  choicefive: Direct Commission
              lineB:
                type: line

          images:
            type: fields
            fields:
              gallery:
                when:
                  toggle_detailpage: true
                min: 1
                required: true
                type: files
                label: Gallery
                query: site.images
                uploads:
                  parent: site
              credit:
                translate: true
                label: Photocredit
                type: writer
                marks:
                  - link
                  - sub
                  - sup
                nodes: false
                placeholder: "Visualisierungen: Name"



  seo: seo/page

options:
  delete:
    editor: true
    admin: true
  changeStatus: true
  move: false
    