title: Project
preset: page

status:
  draft: Draft
  listed: Published


fields:
  header:
    label: Title
    type: text
    required: true

  category:
    label: Category
    type: select
    required: true
    translate: true
    placeholder: !!!
    width: 1/2
    options:
      choiceone: Research
      choicetwo: Sonstige/Spezielles/Privates
      choicethree: Wettbewerb
      choicefour: Wettbewerb gewonnen
      choicefive: Direktauftrag

  information:
    lable: Info
    type: structure
    fields:
      projectDetails:
        label: Project details
        type: select
        options:
          client: Client
          architecture: Architecture
          place: Place
          value: Value
          timeframe: Timeframe
      value:
        label: Value
        type: text
  line:
    type: line
  textTitle:
    label: Text title
    type: text
  text:
    type: textarea
    size: large
    buttons: false

sidebar:
  cover:
    type: files
    label: Cover
    layout: cards
    info: "{{ file.dimensions }}"
    template: cover
    min: 1
    max: 1
    required: true
  gallery:
    type: files
    label: Gallery