title: Project

status:
  draft: Draft
  listed: Published
  unlisted: Privately Published

tabs:
  content:
    label: Content
    icon: text
    columns:
      main:
        width: 2/3
        fields:
          categoryB:
            label: Category
            type: radio
            required: true
            translate: false
            width: 1/2
            options:
              choiceone: Research
              choicetwo: Other
              choicethree: Competition
              choicefour: Competition won
              choicefive: Direct Commission

          tag:
            label: Tag
            type: radio
            required: true
            width: 1/2
            translate: false
            options:
              education: Education
              artInstallation: Art installation
              infrastructure: Infrastructure
              housing: Housing
              research: Research
              serviceAndIndustry: Service and industry
              sportAndCulture: Sport and culture

          information:
            label: Info
            type: structure
            fields:
              projectDetails:
                label: Project details
                type: select
                options:
                  client: Client
                  architecture: Architecture
                  location: Location
                  construction costs: Construction Costs
                  timeframe: Timeframe
                  planification period: Planning Period
                  construction period: Construction Period
                  SIA volume: Volume (SIA)
                  span: Span
                  competition result: Competition Result
                  project phase: Project Phase
                  status: Status
                  construction management: Construction Management
                  general planification: General Planification
                  general contractor: General Contractor
                  total contractor: Total service contractor
                  landscape architecture: Landscape Architecture
                  timber engineer: Timber engineering
                  building services: Building Services
                  electro: Electro
                  building physics: Building Physics
                  collaboration: Collaboration
                  environment: Environment
                  fire protection: Fire life savety
                  facade: Facade
                  light planification: Light Planification
                  mobility: Traffic planning
                  steel construction: Steel Construction
                  concrete construction: Concrete Construction
                  timber construction: Timber Construction
                  natural stone: Natural Stone
                  excavation: Excavation
                  publication: Publication
                  funding: Funding
                  publisher: Publisher
                  institution: Institution
                  credits: Credits


              value:
                label: Value
                type: writer
                marks:
                  - link
                  - sub
                  - sup
                nodes: false
          line:
            type: line
          textTitle:
            label: Text title
            type: text
          text:
            type: writer
            size: large
            marks:
              - link
              - sub
              - sup
            nodes: false

      sidebar:
        width: 1/3
        sticky: true
        sections:
          fieldsA:
            type: fields
            fields:
              listTitle:
                type: writer
                label: List Name
                help: Projectname in the index
                translate: true
                marks: false
                nodes: false
              lineB:
                type: line
          images:
            type: fields
            fields:
              gallery:
                min: 1
                required: true
                type: files
                label: Gallery
                query: site.images
                uploads:
                  parent: site
              credit:
                translate: true
                label: Photocredit
                type: writer
                marks:
                  - link
                  - sub
                  - sup
                nodes: false



  seo: seo/page

options:
  delete:
    editor: true
    admin: true
  changeStatus:
    editor: true
    admin: true
    