title: CO–STRUCT AG

tabs:
  #tab1 PAGES
  pages:
    icon: text
    sections:
      # draft:
      #   type: pages
      #   status: draft
      pages:
        type: pages
        status: published
      fields:
        type: fields
        fields:
          intro:
            label: Introtext
            type: writer
            marks: 
              - link
              - sub
              - sup
            nodes: false
            counter: true
            maxlength: 500
            spellcheck: true

  #tab2 PROJECTS
  projects:
    icon: dashboard
    sections:
      drafts:
        extends: sections/projects
        label: Project Drafts
        status: draft
      
      private:
        extends: sections/projects
        label: Privately Published Drafts
        status: unlisted

      published:
        extends: sections/projects
        label: Published Drafts
        status: listed

  #tab3 INFO CO—STRUCT AG
  Info Co–struct AG:
    icon: pin
    columns:
      main:
        width: 2/3
        sections:
          generalinfo:
            type: fields
            fields:
              info:
                label: General 
                type: info
                theme: positive
                text: The toggle for visibility can be turned off to make an address disappear without deleting it. The visibilty can be targeted separately for the footer and the about page.
              info2:
                label: Footer Info
                type: info
                theme: critical
                text: In the footer a maximum of 3 visible addresses is recommended. If more than 3 addresses are visible, the fourth address will be hidden.
              addresses:
                label: Addresses
                type: structure
                columns:
                  companyName:
                    width: 2/11
                  description:
                    width: 3/11
                  street:
                    width: 3/11
                  place:
                    width: 3/11
                  phoneNumber:
                    width: 3/11
                  toggle:
                    width: 2/11
                  footer_toggle:
                    width: 2/11
                fields:
                  companyName:
                    label: Name
                    type: text
                    width: 1/2
                  description:
                    label: Description
                    type: text
                    width: 1/2
                  street:
                    label: Street
                    type: text
                    width: 1/2
                  place:
                    label: CH—0000 Place
                    type: text
                    width: 1/2
                  phoneNumber:
                    label: Phone Number
                    type: tel
                    width: 1/2
                  toggle:
                    label: About Page
                    type: toggle
                    width: 1/4
                    text: 
                      - "No"
                      - "Yes"
                    default: true
                  footer_toggle:
                    label: Footer
                    type: toggle
                    width: 1/4
                    text: 
                      - "No"
                      - "Yes"
                    default: true

      sidebar:
        width: 1/3
        sections:
          contact:
            type: fields
            fields:
              email:
                label: General Email
                type: email
              instagram:
                label: Instagram Handle
                type: url
              linkedin:
                label: LinkedIn Handle
                type: url

  seo: seo/site

  media:
    icon: images
    sections:
      gallery:
        type: files
        label: Gallery
        layout: cards
        size: small
        limit: 50
        info: "{{ file.dimensions }}"
        image:
          cover: true
          ratio: 1/1
          