title: CO–STRUCT AG

tabs:
        
  #tab1 PAGES
  landing:
    icon: text
    sections:
      pages:
        type: pages
        status: listed
        image:
          icon: false
          query: false
          back: "{{ page.myCustomBackgroundColor }}"

      helper_pages:
        type: pages
        label: Helper Pages
        status: unlisted
        image:
          icon: false
          query: false
          back: "{{ page.myCustomBackgroundColor }}"

  #tab2 INFO CO—STRUCT AG
  Info Co-struct AG:
    label: Info co–struct AG 
    icon: pin
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              intro:
                label: Introtext
                type: writer
                marks: 
                  - link
                  - sub
                  - sup
                nodes: false
                counter: true
                maxlength: 500
                spellcheck: true
          generalinfo:
            type: fields
            fields:
              info:
                label: General 
                type: info
                theme: positive
                text: The toggle for visibility can be turned off to make an address disappear without deleting it. The visibilty can be targeted separately for the footer and the about page.
              addresses:
                label: Addresses
                type: structure
                columns:
                  companyName:
                    width: 2/11
                  description:
                    width: 3/11
                  street:
                    width: 3/11
                  place:
                    width: 3/11
                  phoneNumber:
                    width: 3/11
                  toggle:
                    width: 2/11
                  footer_toggle:
                    width: 2/11
                fields:
                  companyName:
                    label: Name
                    type: text
                    width: 1/2
                  description:
                    label: Description
                    type: text
                    width: 1/2
                  street:
                    label: Street
                    type: text
                    width: 1/2
                  place:
                    label: CH—0000 Place
                    type: text
                    width: 1/2
                  phoneNumber:
                    label: Phone Number
                    type: tel
                    width: 1/2
                  toggle:
                    label: About Page
                    type: toggle
                    width: 1/4
                    text: 
                      - "No"
                      - "Yes"
                    default: true
                  footer_toggle:
                    label: Footer
                    type: toggle
                    width: 1/4
                    text: 
                      - "No"
                      - "Yes"
                    default: true
              info2:
                label: Footer Info
                type: info
                theme: critical
                text: In the footer a maximum of 3 visible addresses is recommended. If more than 3 addresses are visible, the fourth address will be hidden.

      sidebar:
        width: 1/3
        sections:
          contact:
            type: fields
            fields:
              email:
                label: General Email
                type: email
              instagram:
                label: Instagram Handle
                type: url
              linkedin:
                label: LinkedIn Handle
                type: url

  #tab3 MEDIA
  media:
    icon: images
    sections:
      gallery:
        type: files
        label: Gallery
        layout: cards
        size: small
        limit: 50
        info: "{{ file.dimensions }}<br>{{ file.niceSize }}<br>{{ file.alt }}"
        image:
          cover: true
          ratio: 1/1

  seo: seo/site
          