on:
  push:
    branches: main
name: GUIDO Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: [ubuntu-latest]

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Install composer dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.2"
        php_extensions: gd ctype curl mbstring zip
        version: 2.x

    - name: Install npm dependencies
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: |
        npm ci
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.previewServerUrl }}
        username: ${{ secrets.previewusername }}
        password: ${{ secrets.previewpassword }}
        exclude: |
          .htaccess
          **/.git*
          **/.git/**
          **/.github/**
          **/src/**
          **/node_modules/**
           **/content/**
